characters_in_morse = {
    "a": ".-",
    "b": "-...",
    "c": "-.-.",
    "d": "-..",
    "e": ".",
    "f": "..-.",
    "g": "--.",
    "h": "....",
    "i": "..",
    "j": ".---",
    "k": "-.-",
    "l": ".-..",
    "m": "--",
    "n": "-.",
    "o": "---",
    "p": ".--.",
    "r": ".-.",
    "s": "...",
    "t": "-",
    "u": "..-",
    "v": "...-",
    "w": ".--",
    "x": "-..-",
    "y": "-.--",
    "z": "--..",

    "ą": ".-.-",
    "ć": "-.-..",
    "ę": "..-..",
    "ł": ".-..-",
    "ń": "--.--",
    "ó": "---.",
    "ś": "...-...",
    "ż": "--..-.",
    "ź": "--..-",

    "ö": "---.",
    chr(223): "...--..",  # ß
    "ä": ".-.-",
    "æ": ".-.-",
    "à": ".--.-",
    "å": ".--.-",
    "ü": "..--",
    "ĉ": "-.-..",
    "ç": "-.-..",
    "è": ".-..-",
    "é": "..-..",

    "1": ".----",
    "2": "..---",
    "3": "...--",
    "4": "....-",
    "5": ".....",
    "6": "-....",
    "7": "--...",
    "8": "---..",
    "9": "----.",
    "0": "-----",

    ".": ".-.-.-",
    ",": "--..--",
    "'": ".----.",
    "\"": ".-..-.",
    "_": "..--.-",
    ":": "---...",
    ";": "-.-.-.",
    "?": "..--..",
    "!": "-.-.--",
    "-": "-....-",
    "+": ".-.-.",
    "/": "-..-.",
    "(": "-.--.",
    ")": "-.--.-",
    "=": "-...-",
    "@": ".--.-.",
    "&": ".-...",
    "$": "...-..-",

    " ": "/",
}

languages_words = {
    'EN': {
        'title': 'Morse code translator',
        'your_text': 'Your \ntext',
        'morse_message': "Your \nmessage",
        'load_file': 'Open',
        'convert': 'Translate',
        'copy_text': 'Copy',
        'save': 'Save',
        'save_in_direction': 'Save as',
        'load_from_direction': 'Open file'
    },
    'PL': {
        'title': 'Translator Morse\'a',
        'your_text': 'Twój \ntekst',
        'morse_message': "Twoja \nwiadomość",
        'load_file': 'Otwórz',
        'convert': 'Przetłumacz',
        'copy_text': 'Kopiuj',
        'save': 'Zapisz',
        'save_in_direction': 'Zapisz jako',
        'load_from_direction': 'Otwieranie'

    },
    'FRE': {
        'title': 'Traducteur de Morse',
        'your_text': 'Votre \ntext',
        'morse_message': "Votre \nmessage",
        'load_file': 'Ouvrir',
        'convert': 'Traduire ',
        'copy_text': 'Copier',
        'save': 'Enregistrer ',
        'save_in_direction': 'Enregistrer sous',
        'load_from_direction': 'Ouvrir un fichier'

    },
    'GER': {
        'title': 'Morse-Code Übersetzer',
        'your_text': 'Dein \ntext',
        'morse_message': "Morse \ncode",
        'load_file': 'Öffnen',
        'convert': 'Übersetzen',
        'copy_text': 'Kopieren',
        'save': 'Speichern',
        'save_in_direction': 'Speichern unter',
        'load_from_direction': 'Öffnen'

    }
}
